pipeline {
    agent { docker { image 'node:6.3'  }  }
    environment {
        NAME = 'nathan'
    }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
            }
        }
        stage('Check environment') {
            steps {
                sh 'echo $NAME'
            }
        }
        stage('Test node') {
            steps {
                sh 'npm list'
            }
        }
        stage('PWD') {
            steps {
                sh 'echo $PWD'
            }
        }
    }
    post {
        always {
            echo 'Post step!'
        }
    }
}
