pipeline {
    agent { docker { image 'node:6.3'  }  }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
            }
            steps {
                sh 'npm list'
            }
            steps {
                sh 'echo $PWD'
            }
        }
        post {
            always {
                echo 'Post step!'
            }
        }
    }
}
